name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - ydata-profiling=4.5.1
  - matplotlib=3.2.2
  - jupyterlab=4.0.6
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=23.2.1
  - ipywidgets=8.1.1
  - pyarrow=13.0.0
  - pip:
      - wandb==0.15.11