name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.2.1
  - requests=2.31.0
  - mlflow=2.7.1
  - scikit-learn=1.3.1
  - pip:
      - wandb==0.15.11
      - git+https://github.com/culv/ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
