name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.1
  - pip=23.2.1
  - mlflow=2.7.1
  - scikit-learn=1.3.1
  - pip:
      - wandb==0.15.11
      - git+https://github.com/culv/ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
