name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.1.1
  - pip=23.2.1
  - mlflow=2.7.1
  - scikit-learn=1.3.1
  - matplotlib=3.8.0
  - pillow=10.0.1
  - pip:
      - wandb==0.15.11
